/*
 * bSDD API prototype
 * API to access the buildingSMART Data Dictionary
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.rwth_aachen.dc.bsdd_owl.model;


public class DomainContractV2 {
  private String namespaceUri = null;

  private String name = null;

  private String version = null;

  private String organizationNameOwner = null;

  private String defaultLanguageCode = null;

  private String license = null;

  private String licenseUrl = null;

  private String qualityAssuranceProcedure = null;

  private String qualityAssuranceProcedureUrl = null;

public String getNamespaceUri() {
	return namespaceUri;
}

public void setNamespaceUri(String namespaceUri) {
	this.namespaceUri = namespaceUri;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public String getVersion() {
	return version;
}

public void setVersion(String version) {
	this.version = version;
}

public String getOrganizationNameOwner() {
	return organizationNameOwner;
}

public void setOrganizationNameOwner(String organizationNameOwner) {
	this.organizationNameOwner = organizationNameOwner;
}

public String getDefaultLanguageCode() {
	return defaultLanguageCode;
}

public void setDefaultLanguageCode(String defaultLanguageCode) {
	this.defaultLanguageCode = defaultLanguageCode;
}

public String getLicense() {
	return license;
}

public void setLicense(String license) {
	this.license = license;
}

public String getLicenseUrl() {
	return licenseUrl;
}

public void setLicenseUrl(String licenseUrl) {
	this.licenseUrl = licenseUrl;
}

public String getQualityAssuranceProcedure() {
	return qualityAssuranceProcedure;
}

public void setQualityAssuranceProcedure(String qualityAssuranceProcedure) {
	this.qualityAssuranceProcedure = qualityAssuranceProcedure;
}

public String getQualityAssuranceProcedureUrl() {
	return qualityAssuranceProcedureUrl;
}

public void setQualityAssuranceProcedureUrl(String qualityAssuranceProcedureUrl) {
	this.qualityAssuranceProcedureUrl = qualityAssuranceProcedureUrl;
}

  

}
