/*
 * bSDD API prototype
 * API to access the buildingSMART Data Dictionary
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.rwth_aachen.dc.bsdd_owl.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TextSearchResponseClassificationContractV5
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-21T11:35:32.475Z[GMT]")
public class TextSearchResponseClassificationContractV5 {
  @SerializedName("domainNamespaceUri")
  private String domainNamespaceUri = null;

  @SerializedName("domainName")
  private String domainName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("namespaceUri")
  private String namespaceUri = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("parentClassificationName")
  private String parentClassificationName = null;

  @SerializedName("relatedIfcEntityNames")
  private List<String> relatedIfcEntityNames = null;

  public TextSearchResponseClassificationContractV5 domainNamespaceUri(String domainNamespaceUri) {
    this.domainNamespaceUri = domainNamespaceUri;
    return this;
  }

   /**
   * Get domainNamespaceUri
   * @return domainNamespaceUri
  **/
  @Schema(description = "")
  public String getDomainNamespaceUri() {
    return domainNamespaceUri;
  }

  public void setDomainNamespaceUri(String domainNamespaceUri) {
    this.domainNamespaceUri = domainNamespaceUri;
  }

  public TextSearchResponseClassificationContractV5 domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

   /**
   * Get domainName
   * @return domainName
  **/
  @Schema(description = "")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public TextSearchResponseClassificationContractV5 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TextSearchResponseClassificationContractV5 namespaceUri(String namespaceUri) {
    this.namespaceUri = namespaceUri;
    return this;
  }

   /**
   * Namespace URI - unique identification of this classification
   * @return namespaceUri
  **/
  @Schema(description = "Namespace URI - unique identification of this classification")
  public String getNamespaceUri() {
    return namespaceUri;
  }

  public void setNamespaceUri(String namespaceUri) {
    this.namespaceUri = namespaceUri;
  }

  public TextSearchResponseClassificationContractV5 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TextSearchResponseClassificationContractV5 parentClassificationName(String parentClassificationName) {
    this.parentClassificationName = parentClassificationName;
    return this;
  }

   /**
   * Get parentClassificationName
   * @return parentClassificationName
  **/
  @Schema(description = "")
  public String getParentClassificationName() {
    return parentClassificationName;
  }

  public void setParentClassificationName(String parentClassificationName) {
    this.parentClassificationName = parentClassificationName;
  }

  public TextSearchResponseClassificationContractV5 relatedIfcEntityNames(List<String> relatedIfcEntityNames) {
    this.relatedIfcEntityNames = relatedIfcEntityNames;
    return this;
  }

  public TextSearchResponseClassificationContractV5 addRelatedIfcEntityNamesItem(String relatedIfcEntityNamesItem) {
    if (this.relatedIfcEntityNames == null) {
      this.relatedIfcEntityNames = new ArrayList<String>();
    }
    this.relatedIfcEntityNames.add(relatedIfcEntityNamesItem);
    return this;
  }

   /**
   * Get relatedIfcEntityNames
   * @return relatedIfcEntityNames
  **/
  @Schema(description = "")
  public List<String> getRelatedIfcEntityNames() {
    return relatedIfcEntityNames;
  }

  public void setRelatedIfcEntityNames(List<String> relatedIfcEntityNames) {
    this.relatedIfcEntityNames = relatedIfcEntityNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextSearchResponseClassificationContractV5 textSearchResponseClassificationContractV5 = (TextSearchResponseClassificationContractV5) o;
    return Objects.equals(this.domainNamespaceUri, textSearchResponseClassificationContractV5.domainNamespaceUri) &&
        Objects.equals(this.domainName, textSearchResponseClassificationContractV5.domainName) &&
        Objects.equals(this.name, textSearchResponseClassificationContractV5.name) &&
        Objects.equals(this.namespaceUri, textSearchResponseClassificationContractV5.namespaceUri) &&
        Objects.equals(this.description, textSearchResponseClassificationContractV5.description) &&
        Objects.equals(this.parentClassificationName, textSearchResponseClassificationContractV5.parentClassificationName) &&
        Objects.equals(this.relatedIfcEntityNames, textSearchResponseClassificationContractV5.relatedIfcEntityNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domainNamespaceUri, domainName, name, namespaceUri, description, parentClassificationName, relatedIfcEntityNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextSearchResponseClassificationContractV5 {\n");
    
    sb.append("    domainNamespaceUri: ").append(toIndentedString(domainNamespaceUri)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespaceUri: ").append(toIndentedString(namespaceUri)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parentClassificationName: ").append(toIndentedString(parentClassificationName)).append("\n");
    sb.append("    relatedIfcEntityNames: ").append(toIndentedString(relatedIfcEntityNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
