/*
 * bSDD API prototype
 * API to access the buildingSMART Data Dictionary
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.rwth_aachen.dc.bsdd_owl.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TextSearchResponsePropertyContractV5
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-21T11:35:32.475Z[GMT]")
public class TextSearchResponsePropertyContractV5 {
  @SerializedName("domainNamespaceUri")
  private String domainNamespaceUri = null;

  @SerializedName("domainName")
  private String domainName = null;

  @SerializedName("namespaceUri")
  private String namespaceUri = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  public TextSearchResponsePropertyContractV5 domainNamespaceUri(String domainNamespaceUri) {
    this.domainNamespaceUri = domainNamespaceUri;
    return this;
  }

   /**
   * Get domainNamespaceUri
   * @return domainNamespaceUri
  **/
  @Schema(description = "")
  public String getDomainNamespaceUri() {
    return domainNamespaceUri;
  }

  public void setDomainNamespaceUri(String domainNamespaceUri) {
    this.domainNamespaceUri = domainNamespaceUri;
  }

  public TextSearchResponsePropertyContractV5 domainName(String domainName) {
    this.domainName = domainName;
    return this;
  }

   /**
   * Get domainName
   * @return domainName
  **/
  @Schema(description = "")
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(String domainName) {
    this.domainName = domainName;
  }

  public TextSearchResponsePropertyContractV5 namespaceUri(String namespaceUri) {
    this.namespaceUri = namespaceUri;
    return this;
  }

   /**
   * Get namespaceUri
   * @return namespaceUri
  **/
  @Schema(description = "")
  public String getNamespaceUri() {
    return namespaceUri;
  }

  public void setNamespaceUri(String namespaceUri) {
    this.namespaceUri = namespaceUri;
  }

  public TextSearchResponsePropertyContractV5 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TextSearchResponsePropertyContractV5 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextSearchResponsePropertyContractV5 textSearchResponsePropertyContractV5 = (TextSearchResponsePropertyContractV5) o;
    return Objects.equals(this.domainNamespaceUri, textSearchResponsePropertyContractV5.domainNamespaceUri) &&
        Objects.equals(this.domainName, textSearchResponsePropertyContractV5.domainName) &&
        Objects.equals(this.namespaceUri, textSearchResponsePropertyContractV5.namespaceUri) &&
        Objects.equals(this.name, textSearchResponsePropertyContractV5.name) &&
        Objects.equals(this.description, textSearchResponsePropertyContractV5.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domainNamespaceUri, domainName, namespaceUri, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextSearchResponsePropertyContractV5 {\n");
    
    sb.append("    domainNamespaceUri: ").append(toIndentedString(domainNamespaceUri)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    namespaceUri: ").append(toIndentedString(namespaceUri)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
