/*
 * bSDD API prototype
 * API to access the buildingSMART Data Dictionary
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.rwth_aachen.dc.bsdd_owl.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TextSearchResponseContractV5
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-21T11:35:32.475Z[GMT]")
public class TextSearchResponseContractV5 {
  @SerializedName("classifications")
  private List<TextSearchResponseClassificationContractV5> classifications = null;

  @SerializedName("domains")
  private List<TextSearchResponseDomainContractV5> domains = null;

  @SerializedName("properties")
  private List<TextSearchResponsePropertyContractV5> properties = null;

  public TextSearchResponseContractV5 classifications(List<TextSearchResponseClassificationContractV5> classifications) {
    this.classifications = classifications;
    return this;
  }

  public TextSearchResponseContractV5 addClassificationsItem(TextSearchResponseClassificationContractV5 classificationsItem) {
    if (this.classifications == null) {
      this.classifications = new ArrayList<TextSearchResponseClassificationContractV5>();
    }
    this.classifications.add(classificationsItem);
    return this;
  }

   /**
   * The list of Classifications found
   * @return classifications
  **/
  @Schema(description = "The list of Classifications found")
  public List<TextSearchResponseClassificationContractV5> getClassifications() {
    return classifications;
  }

  public void setClassifications(List<TextSearchResponseClassificationContractV5> classifications) {
    this.classifications = classifications;
  }

  public TextSearchResponseContractV5 domains(List<TextSearchResponseDomainContractV5> domains) {
    this.domains = domains;
    return this;
  }

  public TextSearchResponseContractV5 addDomainsItem(TextSearchResponseDomainContractV5 domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<TextSearchResponseDomainContractV5>();
    }
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  @Schema(description = "")
  public List<TextSearchResponseDomainContractV5> getDomains() {
    return domains;
  }

  public void setDomains(List<TextSearchResponseDomainContractV5> domains) {
    this.domains = domains;
  }

  public TextSearchResponseContractV5 properties(List<TextSearchResponsePropertyContractV5> properties) {
    this.properties = properties;
    return this;
  }

  public TextSearchResponseContractV5 addPropertiesItem(TextSearchResponsePropertyContractV5 propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<TextSearchResponsePropertyContractV5>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @Schema(description = "")
  public List<TextSearchResponsePropertyContractV5> getProperties() {
    return properties;
  }

  public void setProperties(List<TextSearchResponsePropertyContractV5> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextSearchResponseContractV5 textSearchResponseContractV5 = (TextSearchResponseContractV5) o;
    return Objects.equals(this.classifications, textSearchResponseContractV5.classifications) &&
        Objects.equals(this.domains, textSearchResponseContractV5.domains) &&
        Objects.equals(this.properties, textSearchResponseContractV5.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classifications, domains, properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextSearchResponseContractV5 {\n");
    
    sb.append("    classifications: ").append(toIndentedString(classifications)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
